// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_4aaXz_7Gy0ACXBPMjU4t6NMjgFr8Lzw',
    appId: '1:918363992232:web:986f8a0d51e50c4882d29d',
    messagingSenderId: '918363992232',
    projectId: 'flutter-app-e4418',
    authDomain: 'flutter-app-e4418.firebaseapp.com',
    storageBucket: 'flutter-app-e4418.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDmKWeKRlC199z6cw5_ihM4jgzcDwhRU',
    appId: '1:918363992232:android:c74c00caa29ba27882d29d',
    messagingSenderId: '918363992232',
    projectId: 'flutter-app-e4418',
    storageBucket: 'flutter-app-e4418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKs2QI9iaD36LE19RbN-_JVCvOLZ06Htw',
    appId: '1:918363992232:ios:d0a6c2ca07c93f6482d29d',
    messagingSenderId: '918363992232',
    projectId: 'flutter-app-e4418',
    storageBucket: 'flutter-app-e4418.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKs2QI9iaD36LE19RbN-_JVCvOLZ06Htw',
    appId: '1:918363992232:ios:d0a6c2ca07c93f6482d29d',
    messagingSenderId: '918363992232',
    projectId: 'flutter-app-e4418',
    storageBucket: 'flutter-app-e4418.firebasestorage.app',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_4aaXz_7Gy0ACXBPMjU4t6NMjgFr8Lzw',
    appId: '1:918363992232:web:12af0ca0a94b198582d29d',
    messagingSenderId: '918363992232',
    projectId: 'flutter-app-e4418',
    authDomain: 'flutter-app-e4418.firebaseapp.com',
    storageBucket: 'flutter-app-e4418.firebasestorage.app',
  );
}
